languageCode = "en-us"
title = "Petr Ruzicka"
baseURL = "https://petr.ruzicka.dev/"
theme = "aerial"

[params]
  name = "Petr Růžička"
  about = "DevOps &nbsp;&bull;&nbsp; SysAdmin &nbsp;&bull;&nbsp; Photographer"
  #copyright = "Untitled"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.ico"

# Professional/Work/Contacts
[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:petr.ruzicka@gmail.com"

[[params.social]]
  medium = "Home Page"
  icon = "home"
  link = "https://ruzickap.github.io"

[[params.social]]
  medium = "LinkedIn"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/petrruzicka/"

[[params.social]]
  medium = "GitHub"
  icon = "github"
  link = "https://github.com/ruzickap/"

# Social Media
[[params.social]]
  medium = "Mastodon"
  icon = "mastodon"
  link = "https://mastodon.social/@ruzickap"

[[params.social]]
  medium = "Facebook"
  icon = "facebook"
  link = "https://www.facebook.com/petr.ruzicka"

[[params.social]]
  medium = "Instagram"
  icon = "instagram"
  link = "https://www.instagram.com/petr.ruzicka_cz/"

# Photography
[[params.social]]
  medium = "500px"
  icon = "500px"
  link = "https://500px.com/petrruzicka"

[[params.social]]
  medium = "Flickr"
  icon = "flickr"
  link = "https://www.flickr.com/photos/petrruzicka/"

[[params.social]]
  medium = "Pixabay"
  icon = "camera"
  link = "https://pixabay.com/users/ruzickap-7967890/"

[[params.social]]
  medium = "Unsplash"
  icon = "camera-retro"
  link = "https://unsplash.com/@ruzickap/"
