baseURL = "https://example.com/"
languageCode = "en-us"
title = "Petr Ruzicka"
theme = "LucentLink-Hugo"
minVersion = "0.115.0"

[params]
  description     = "Petr Ruzicka's personal website - DevSecOps specialist, SysAdmin, and photographer."
  googleAnalytics = ""    # your GA ID, if any

[outputs]
  home = ["HTML"]
